declare module 'unfetch'
declare module 'array-to-sentence'
declare module 'balloon-css'
declare module 'mkdir-promise'
declare module 'ipchecker'
declare module 'truncate'
declare module 'flatten'
declare module 'promise-queue-plus'
declare module 'promise.series'
declare module 'memory-fs'
declare module 'strip-markdown'
declare module 'remark'
declare module 'uglifyjs-webpack-plugin'
declare module 'hot-shots'
declare module 'is-empty-object'
declare module 'big-json'
declare module 'performance-now'
declare module 'natural'
declare module 'workerpool'
declare module 'pacote'
declare module 'git-url-parse'

declare const amplitude: any
